### ISSUE TITLE
Design Remote Mining Outposts (for Maintenance Factory)

### ISSUE THREAD

**Issue by curiousinternals** [bug-quota/slime.factorio#13]
The outposts will need the following components:
- [ ] Internal (defence) power (#14)
- [ ] Exports/Imports depot (perhaps based on #9, but the output rates can probably be lower)
- [ ] Defence (#7)
- [x] Mining drills (#15)
- [ ] Buffers? (#5 or the vehicle depot might act as a buffer. Buffer size depends on how many vehicles are available to wait)

Share designs under game blueprints.
