### ISSUE TITLE
Design Maintenance Factory

### ISSUE THREAD

**Issue by curiousinternals** [bug-quota/slime.factorio#2]
Each component of the maintenance factory ought to be designed ahead of time in order to make the layout of the factory easier to determine. Ideally, the factory should be kept as small as possible to minimise defence costs.

Required top-level components:
- [x] Smelters (#3)
- [ ] Ammo production (Red mags) (#4)
- [ ] Buffers (#5)
- [ ] Replacement Parts Manufacturing (#6)
- [ ] Defences (#7)
- [ ] Vehicle Replacement (#8)
- [ ] Imports/Exports Depot (#9)
- [ ] Vehicle C&C Centre (#10)
- [ ] Exports Rail Station (#11)
- [ ] Power Generation (#12)

We also need designs for remote mining outposts (#13).

Share designs under game blueprints.
